

# GET http://localhost:5000/products
# Content-Type: application/json

# {
#     "name": "Huawei"
# }

# POST http://localhost:5000/addToCart/64747a3811c9ebe3d8a6613f
# get http://localhost:5000/viewcart/

# 64747a3011c9ebe3d8a6613d
# 64747a3811c9ebe3d8a6613f

# GET http://localhost:5000/products

# POST http://localhost:5000/newbrand
# Content-Type: application/json

# {
#     "name": "Oppo"
# }

# 64649107ff6c8eccfe2787e9

# PUT http://localhost:5000/products/edit/6464d972177f3dbed8e4f595
# Content-Type: application/json

# {
#   "name": "Oppo",
#   "brand": "64649107ff6c8eccfe2787e9",
#   "price": 333,
#   "description": "ddđ",
#   "colors": [ "eee" ],
#   "specs": [ "ddd" ]
# }



# GET http://localhost:5000/brands
# POST http://localhost:5000/newproduct
# Content-Type: application/json

# {
# "name": "DDDDDDDDDDDo",
# "brand": "645f8cd29908832439f3302f",
# "price": 34341,
# "stock": 3,
# "description": "DAWMJKDKOWADJWAIOWA"
# }

# DELETE  http://localhost:5000/products/delete/6467334dcb6f0eeb50c7cc68

# GET http://localhost:5000/products

# POST http://localhost:5000/addToCart/64747a3011c9ebe3d8a6613d

# GET http://localhost:5000/viewcart

# GET http://localhost:5000/orders

# POST http://localhost:5000/neworder
# Content-Type: application/json

# {
#   "user": "John Doe",
#   "status": 1,
#   "address": "123 Main St"
# }


# POST http://localhost:5000/register
# Content-Type: application/json

# {
#   "firstname": "John",
#   "lastname": "Doe",
#   "email": "lekecas806@ratedane.com",
#   "password": "Bandicam_123123"
# }

POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "lekecas806@ratedane.com",
  "password": "Bandicam_123123"
}

# DELETE http://localhost:5000/Deleteallorders

# View all orders
# GET http://localhost:5000/orders

# DELETE http://localhost:5000/Deleteallorders

